### ISSUE TITLE
px-doc:document-csv not appearing as expected

### ISSUE THREAD

**Issue by mailmrmanoj** [predixdesignsystem/px-icon-set#13]
I tried to include px csv icon by first importing 
`<link rel="import" href="bower_components/px-icon-set/px-icon-set.html" />
`
and also tried by having below two files as an alternative
```
<link rel="import" href="bower_components/px-icon-set/px-icon.html" />
<link rel="import" href="bower_components/px-icon-set/px-icon-set-document.html" />
```

But appearing as show below which works fine for other icons like filter.Is there any other dependency needs to be added for document icons ?
![excel download](https://user-images.githubusercontent.com/7077567/34294292-cda50638-e72d-11e7-9a70-454e5074a1eb.PNG)

**Comment by randyaskin** [comment]
Your first import is correct and should be the only one needed. 

This shouldn't be possible with style encapsulation, but it looks like you are somehow impacting the font-size of the letters "CSV" inside of the icon - I can create something similar in Chrome inspector by targeting the `text` element deep inside of the px-icon and overriding the font-size to be 30px instead of 7px.
